### ISSUE TITLE
Table 'chimera_db.CONTROLNODEINSTANCE' doesn't exist

### ISSUE THREAD

**Issue by tommartensen** [bptlab/chimera#117]
During the regular persisting of the cases, this error occurs: 
````
 Call: SELECT ID, DTYPE, STATE, CONTROLNODE_DBID, FRAGMENTINSTANCE_ID, HASAUTOMATICBEGIN, BEHAVIOR_DBID, PREVIOUSEVENTBASEDGATEWAYINSTANCE_ID FROM CONTROLNODEINSTANCE WHERE ((ID = ?) AND (DTYPE = ?))
chimera_1   |   bind => [5eec4b04ac7e4c038c74e197d378846f, StartEventInstance]
chimera_1   | Query: ReadObjectQuery(referenceClass=StartEventInstance )
chimera_1   |   at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
chimera_1   |   at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:684)
chimera_1   |   at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
chimera_1   |   at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2056)
chimera_1   |   at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
chimera_1   |   at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
chimera_1   |   at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
chimera_1   |   at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:714)
chimera_1   |   at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2803)
chimera_1   |   at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2756)
chimera_1   |   at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:555)
chimera_1   |   at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1175)
chimera_1   |   at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
chimera_1   |   at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
chimera_1   |   at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:441)
chimera_1   |   at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
chimera_1   |   at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
chimera_1   |   at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
chimera_1   |   at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
chimera_1   |   at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1790)
chimera_1   |   at org.eclipse.persistence.internal.sessions.AbstractSession.readObject(AbstractSession.java:3720)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.registerObjectForMergeCloneIntoWorkingCopy(MergeManager.java:1100)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChangesOfCloneIntoWorkingCopy(MergeManager.java:564)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChanges(MergeManager.java:313)
chimera_1   |   at org.eclipse.persistence.mappings.CollectionMapping.mergeIntoObject(CollectionMapping.java:1645)
chimera_1   |   at org.eclipse.persistence.internal.descriptors.ObjectBuilder.mergeIntoObject(ObjectBuilder.java:4136)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChangesOfCloneIntoWorkingCopy(MergeManager.java:601)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChanges(MergeManager.java:313)
chimera_1   |   at org.eclipse.persistence.mappings.CollectionMapping.mergeIntoObject(CollectionMapping.java:1645)
chimera_1   |   at org.eclipse.persistence.internal.descriptors.ObjectBuilder.mergeIntoObject(ObjectBuilder.java:4136)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChangesOfCloneIntoWorkingCopy(MergeManager.java:601)
chimera_1   |   at org.eclipse.persistence.internal.sessions.MergeManager.mergeChanges(MergeManager.java:313)
chimera_1   |   at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3521)
chimera_1   |   at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.mergeCloneWithReferences(RepeatableWriteUnitOfWork.java:387)
chimera_1   |   at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3481)
chimera_1   |   at org.eclipse.persistence.internal.jpa.EntityManagerImpl.mergeInternal(EntityManagerImpl.java:553)
chimera_1   |   at org.eclipse.persistence.internal.jpa.EntityManagerImpl.merge(EntityManagerImpl.java:530)
chimera_1   |   at de.hpi.bpt.chimera.persistencemanager.DomainModelPersistenceManager.saveAllCaseModelsWithCases(DomainModelPersistenceManager.java:148)
chimera_1   |   at de.hpi.bpt.chimera.persistencemanager.CasePersistenceTask.run(CasePersistenceTask.java:58)
chimera_1   |   at java.util.TimerThread.mainLoop(Timer.java:555)
chimera_1   |   at java.util.TimerThread.run(Timer.java:505)
chimera_1   | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'chimera_db.CONTROLNODEINSTANCE' doesn't exist
chimera_1   |   at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
chimera_1   |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
chimera_1   |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
chimera_1   |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
chimera_1   |   at com.mysql.jdbc.Util.getInstance(Util.java:408)
chimera_1   |   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
chimera_1   |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
chimera_1   |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
chimera_1   |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
chimera_1   |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
chimera_1   |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
chimera_1   |   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
chimera_1   |   at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
chimera_1   |   at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1009)
chimera_1   |   at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:644)
chimera_1   |   ... 39 more
chimera_1   | ERROR 2018-06-27 11:50:41,467 [Timer-0][CasePersistenceTask.java:60] : Error while persisting all CaseModels and Cases
chimera_1   | javax.persistence.RollbackException: Transaction "rolled back" because transaction was set to RollbackOnly.
chimera_1   |   at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:143)
chimera_1   |   at de.hpi.bpt.chimera.persistencemanager.DomainModelPersistenceManager.saveAllCaseModelsWithCases(DomainModelPersistenceManager.java:162)
chimera_1   |   at de.hpi.bpt.chimera.persistencemanager.CasePersistenceTask.run(CasePersistenceTask.java:58)
chimera_1   |   at java.util.TimerThread.mainLoop(Timer.java:555)
chimera_1   |   at java.util.TimerThread.run(Timer.java:505)
chimera_1   | [EL Warning]: 2018-06-27 11:50:51.49--UnitOfWork(80931150)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.DatabaseException
```

Instead, the table `CONTROLNODEINSTANCE_CONTROLNODE_INSTANCE` exists.

**Comment by tommartensen** [comment]
FYI: this issue also occurs on completely new deployments.

**Comment by Tobias314** [comment]
Should work now. The field webServiceJson in WebServiceTaskInstance was too long. See the corresponding commit.
