### ISSUE TITLE
[Error][Deployment] Error while persisting all CaseModels and cases

### ISSUE THREAD

**Issue by julianweise** [bptlab/chimera#118]
The following error occurs within `Chimera` while deploying [this model](https://github.com/bptlab/chimera/files/2145858/5b20cdd4e4c8490021e2d7ad.1.json.zip)
 from `Gryphon` to `Chimera`:

```
2018-06-28 15:13:43,019 ERROR [de.hpi.bpt.chimera.persistencemanager.CasePersistenceTask] - Error while persisting all CaseModels and Cases
javax.persistence.RollbackException: Transaction "rolled back" because transaction was set to RollbackOnly.
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:143)
	at de.hpi.bpt.chimera.persistencemanager.DomainModelPersistenceManager.saveAllCaseModelsWithCases(DomainModelPersistenceManager.java:162)
	at de.hpi.bpt.chimera.persistencemanager.CasePersistenceTask.run(CasePersistenceTask.java:58)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by tommartensen** [comment]
Duplicates #117
