### ISSUE TITLE
cases for case model not retrieved from database

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#83]
This error occurred on the bpt-bookshelf/chimera that runs on our Docker-VM. Problem is a non existing table `CaseExecutioner`. Does the database schema needs to be updated somehow? 
```
2018-06-05 09:09:59,175 ERROR [de.hpi.bpt.chimera.persistencemanager.DomainModelPersistenceManager] - Error while loading all Cases of a CaseModel Id from database
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'JEngineV2_ChimeraDev.CaseExecutioner' doesn't exist
Error Code: 1146
Call: SELECT * FROM CaseExecutioner ce WHERE ce.CASEMODEL_CMID = '23c9eee3cff64082978086cecc3dd29e';
Query: ReadAllQuery(referenceClass=CaseExecutioner sql="SELECT * FROM CaseExecutioner ce WHERE ce.CASEMODEL_CMID = '23c9eee3cff64082978086cecc3dd29e';")
        at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
        at de.hpi.bpt.chimera.persistencemanager.DomainModelPersistenceManager.loadAllCaseExecutionersWithCaseModelId(DomainModelPersistenceManager.java:183)
        at de.hpi.bpt.chimera.execution.ExecutionService.getAllCasesOfCaseModel(ExecutionService.java:180)
        at de.hpi.bpt.chimera.rest.ScenarioInstanceRestService.getScenarioInstances(ScenarioInstanceRestService.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
```

**Comment by marhew** [comment]
The table is named `CASEEXECUTIONER` and not `Case Executioner`...
```
mysql> SELECT * FROM CaseExecutioner ce WHERE ce.CASEMODEL_CMID = '23c9eee3cff64082978086cecc3dd29e';
ERROR 1146 (42S02): Table 'JEngineV2_ChimeraDev.CaseExecutioner' doesn't exist
mysql> SELECT * FROM CASEEXECUTIONER ce WHERE ce.CASEMODEL_CMID = '23c9eee3cff64082978086cecc3dd29e';
+------+---------------------------+----------------------------------+------------------+
| DBID | CaseExecutionerTerminated | CASEMODEL_CMID                   | DATAMANAGER_DBID |
+------+---------------------------+----------------------------------+------------------+
|   97 |                         0 | 23c9eee3cff64082978086cecc3dd29e |               98 |
|  108 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              109 |
|  151 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              152 |
|  162 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              163 |
|  201 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              202 |
|  251 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              252 |
|  262 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              263 |
|  386 |                         0 | 23c9eee3cff64082978086cecc3dd29e |              387 |
+------+---------------------------+----------------------------------+------------------+
8 rows in set (0.00 sec)
```

**Comment by tommartensen** [comment]
This has very high priority for the Bookshelf project, as we are blocked from executing cases on Chimera (Bug is also in local deployment). Please ping us, once this is fixed.
